"""Structured HTTP errors, handlers, and OpenAPI response schemas."""

from .base import BaseHTTPException
from .handlers import (
    EXCEPTION_HANDLERS,
    base_http_exception_handler,
    general_exception_handler,
    mongodb_exception_handler,
    pydantic_exception_handler,
    request_validation_exception_handler,
)
from .mongodb import (
    DocumentAlreadyExistsError,
    DocumentDuplicateKeyError,
    DocumentNotFoundError,
    MongoDBConnectionError,
    MongoDBError,
    MongodbOperationTimeoutError,
    MongoDBTimeoutError,
    MultipleDocumentsFoundError,
    convert_pymongo_error,
    find_pymongo_error,
)
from .redis import RedisConnectionError
from .resource import (
    ResourceAlreadyExistsError,
    ResourceConflictError,
    ResourceForbiddenError,
    ResourceGoneError,
    ResourceLockedError,
    ResourceNotFoundError,
    ResourcePaymentRequiredError,
)
from .responses import (
    COMMON_ERROR_RESPONSES,
    APIErrorResponseModel,
    InternalErrorResponseModel,
    ValidationErrorResponseModel,
    ValidationReason,
    setup_openapi_errors,
)
from .status import (
    AlreadyExistsError,
    BadRequestError,
    ConflictError,
    FeatureNotImplementedError,
    ForbiddenError,
    GatewayTimeoutError,
    GoneError,
    LockedError,
    MethodNotAllowedError,
    NotFoundError,
    PaymentRequiredError,
    PreconditionFailedError,
    ServerError,
    ServiceUnavailableError,
    TeaPotError,
    TooManyRequestsError,
    UnauthorizedError,
)

__all__ = [
    "COMMON_ERROR_RESPONSES",
    "EXCEPTION_HANDLERS",
    "APIErrorResponseModel",
    "AlreadyExistsError",
    "BadRequestError",
    "BaseHTTPException",
    "ConflictError",
    "DocumentAlreadyExistsError",
    "DocumentDuplicateKeyError",
    "DocumentNotFoundError",
    "FeatureNotImplementedError",
    "ForbiddenError",
    "GatewayTimeoutError",
    "GoneError",
    "InternalErrorResponseModel",
    "LockedError",
    "MethodNotAllowedError",
    "MongoDBConnectionError",
    "MongoDBError",
    "MongoDBTimeoutError",
    "MongodbOperationTimeoutError",
    "MultipleDocumentsFoundError",
    "NotFoundError",
    "PaymentRequiredError",
    "PreconditionFailedError",
    "RedisConnectionError",
    "ResourceAlreadyExistsError",
    "ResourceConflictError",
    "ResourceForbiddenError",
    "ResourceGoneError",
    "ResourceLockedError",
    "ResourceNotFoundError",
    "ResourcePaymentRequiredError",
    "ServerError",
    "ServiceUnavailableError",
    "TeaPotError",
    "TooManyRequestsError",
    "UnauthorizedError",
    "ValidationErrorResponseModel",
    "ValidationReason",
    "base_http_exception_handler",
    "convert_pymongo_error",
    "find_pymongo_error",
    "general_exception_handler",
    "mongodb_exception_handler",
    "pydantic_exception_handler",
    "request_validation_exception_handler",
    "setup_openapi_errors",
]
